export default {
    chinese: {
        SAPTasks:'SAP任务',
        TimingPlan:'定时计划',
        ManualTasks:'手动任务',
        addBtn: '新增',
        editBtn: '修改',
        deleteBtn: '删除',
        searchBtn: '查询',
        sampleName: '样品名称',
        sampleBatchNumber: '样品批号',
        sampleNo: '样品编号',
        warehousingDate: '入库日期',
        supplier: '供应商',
        team: '班组',
        viewScope: '查看范围',
        taskStatus: '任务状态',
        inspectionType: '检验类型',
        oneself: '本人',
        department: '本部门',
        whole: '全部',
        Reset: '重置',
        SerialNumber: '序号',
        PlannedDate: '计划日期',
        TaskDate: '任务日期',
        SamplingPoint: '采样点',
        productionLine: '生产线',
        SampledBy: '采样人',
        SubcontractingOrNot: '是否分包',
        startTime:'开始时间',
        EndTime:'结束时间',
        PleaseSelect: '请选择',
        NoDataTemporarily:'暂无数据',
        ScheduledTask:'定时任务'
    },
    english: {
        SAPTasks:'SAP Tasks',
        TimingPlan:'Timing Plan',
        ManualTasks:'Manual Tasks',
        addBtn: 'Add',
        editBtn: 'Edit',
        deleteBtn: 'Delete',
        searchBtn: 'Search',
        sampleName: 'Sample Name',
        sampleBatchNumber: 'sample Batch Number',
        sampleNo: 'Sample No',
        warehousingDate: 'Warehousing Date',
        supplier: 'Supplier',
        team: 'Team',
        viewScope: 'View Scope',
        taskStatus: 'Task Status',
        inspectionType: 'Inspection Type',
        oneself: 'Oneself',
        department: 'Department',
        whole: 'Whole',
        Reset: 'Reset',
        SerialNumber: 'Order',
        PlannedDate: 'Planned Date',
        SamplingPoint: 'Sampling Point',
        productionLine: 'Production Line',
        TaskDate: 'Task Date',
        SampledBy: 'Sampled By',
        SubcontractingOrNot:'Subcontracting Or Not',
        startTime:'Start Time',
        EndTime:'End Time',
        PleaseSelect: 'Please Select',
        NoDataTemporarily:'No Data Temporarily',
        ScheduledTask:'Scheduled Task'
    }
}
