export default {
    chinese: {
        SAPTasks:'SAP任务',
        TimingPlan:'定时计划',
        ManualTasks:'手动任务',
        addBtn: '新增',
        editBtn: '修改',
        deleteBtn: '删除',
        searchBtn: '查询',
        batchSubmission: '批量提交',
        batchDelete: '批量删除',
        processView: '流程查看',
        printSampleLabel: '打印样品标签',
        seriaNumber: '序号',
        order: '序号',
        inspectionType: '检验类型',
        taskNumber: '任务编号',
        sampleBatchNumber: '样品批号',
        sampleNo: '样品编号',
        team: '班组',
        sampleName: '样品名称',
        sampleNumber: '样品数量',
        supplier: '供应商',
        inspectionID: '检验批ID',
        manufactureDate: '生产日期',
        warehousingDate: '入库日期',
        taskDate: '任务日期',
        state: '状态',
        see: '查看',
        withdraw: '撤回',
        delete: '删除',
        Submit: '提交',
        edit: '编辑',
        taskName: '任务名称',
        taskInfo: '任务信息',
        sampleInfo: '样品信息',
        testApplicant: '检测申请人',
        applicationDate: '申请检测日期',
        ContactWay: '申请人联系方式',
        supplierTelephone: '供应商电话',
        supplierAddress: '供应商地址',
        detectionNature: '检测性质',
        completionDate: '要求完成日期',
        retentionSampleProcessing: '留样处理',
        taskNotes: '任务备注',
        quantityUnit: '数量单位',
        sampleSpecification: '样品规格',
        inspectionQuantity: '检验数量',
        InspectionType: '检验类型',
        StorageConditions: '保存条件',
        SampleMorphology: '样品形态',
        termValidity: '有效期',
        Sampledescription: '样品描述',
        PleaseEnter: '请输入',
        DetectionGroup: '检测组',
        TemporaryStorage: '暂存',
        cancel: '取消',
        AddTestItems: '新增检测项目',
        EssentialInformation: '基本信息',
        TestItems: '检测项目',
        TestItemName: '检测项目名称',
        StandardNo: '标准编号',
        StandardName: '标准名称',
        TestingPost: '检测岗位',
        Operation: '操作',
        remarks: '备注',
        withdrawalReason: '撤回原因',
        PleaseSelect: '请选择',
        SamplingPoint: '采样点',
        productionLine: '生产线',
        SubcontractingOrNot: '是否分包',
        Subcontractor: '分包商',
        WhetherToSignAContract: '是否签订合同',
        ResultJudgmentBasis: '结果判定依据',
        Fermentation: '是否发酵任务',
        FermentationStartTime: '发酵开始时间',
        FermentationEndTime: '发酵结束时间',
        FermentationPeriod: '发酵时间段',
        PlanNumber: '计划编号',
        PlanName: '计划名称',
        planDate: '计划日期',
        PlannedSamplingDate: '计划采样日期',
        StartSamplingDate: '开始采样日期',
        ActualSamplingTime: '实际采样时间',
        SamplingPeriod: '采样时间段',
        StartSamplingTime: '开始采样时间',
        SampleRumberingRules: '样品编号规则',
        preservation: '保存',
        DetermineThePlan: '确定计划',
        speedOfProgress: '进度',
        SelectDate: '选择日期',
        ItemsSelected: '已选择项目',
        TestAndDetectionParameters: '试验检测参数',
        TestBasisNo: '试验检测依据编号',
        MethodCode: '方法编号',
        MethodName: '方法名称',
        GroupName: '分组名称',
        Reset: '重置',
        ByProject: '按项目',
        GroupBy: '按分组',
        AddTestPlan:'新增检测计划',
        DividePlangroups:'划分计划组',
        frequency:'频率',
        timeSlot:'时间段',
        DetermineFrequency:'确定频次',
        NoDataTemporarily:'暂无数据',
        ApprovalTime:'审批时间',
        Approver:'审批人',
        ApprovalOpinions:'审批意见',
        WithdrawalDetails:'撤回详情',
        ScheduledTask:'定时任务',
        TestPlanPeriod:'检测计划时间段',
        TasksTimes:'任务次',
        SchedulingPlan: '计划排程',
        NewSchedule: '新增排程',
        download: '下载',
        Schedule: '排程',
        TaskProgress: '任务进度',
        DetectionProgress: '检测进度',
        ReportProgress: '报告进度',
        PlanRemarks:'计划备注',
        ActualSamplingOffsetMinutes:'实际取样偏移分钟数'
    },
    english: {
        SAPTasks:'SAP Tasks',
        TimingPlan:'Timing Plan',
        ManualTasks:'Manual Tasks',
        addBtn: 'Add',
        editBtn: 'Edit',
        deleteBtn: 'Delete',
        searchBtn: 'Search',
        batchSubmission: 'Batch Submission',
        batchDelete: 'Batch Delete',
        processView: 'Process View',
        printSampleLabel: 'Print Sample Label',
        seriaNumber: 'Order',
        order: 'Order',
        inspectionType: 'Inspection Type',
        taskNumber: 'Task Number',
        sampleBatchNumber: 'sample Batch Number',
        sampleNo: 'Sample No',
        team: 'Team',
        sampleName: 'Sample Name',
        sampleNumber: 'Sample Number',
        supplier: 'Supplier',
        inspectionID: 'Inspection Lot ID',
        manufactureDate: 'Date Of Manufacture',
        warehousingDate: 'Warehousing Date',
        taskDate: 'Task Date',
        state: 'State',
        see: 'See',
        withdraw: 'Withdraw',
        delete: 'Delete',
        Submit: 'Submit',
        edit: 'Edit',
        taskName: 'Task Name',
        taskInfo: 'Task Info',
        sampleInfo: 'Sample Info',
        testApplicant: 'Test Applicant',
        applicationDate: 'Date Of Application For Testing',
        ContactWay: 'Contact Information Of The Applicant',
        supplierTelephone: 'Supplier Telephone',
        supplierAddress: 'Supplier Address',
        detectionNature: 'Detection Nature',
        completionDate: 'Required Completion Date',
        retentionSampleProcessing: 'Retention Sample Processing',
        taskNotes: 'Task Notes',
        quantityUnit: 'Quantity Unit',
        sampleSpecification: 'Sample Specification',
        inspectionQuantity: 'Inspection Quantity',
        InspectionType: 'Inspection Type',
        StorageConditions: 'Storage Monditions',
        SampleMorphology: 'Sample Morphology',
        termValidity: 'Term Of Validity',
        Sampledescription: 'Sample Description',
        PleaseEnter: 'Please Enter',
        DetectionGroup: 'Detection Group',
        TemporaryStorage: 'Temporary Storage',
        cancel: 'cancel',
        AddTestItems: 'Add Test Items',
        EssentialInformation: 'Essential Information',
        TestItems: 'Test Items',
        TestItemName: 'Test Item Name',
        StandardNo: 'Standard No',
        StandardName: 'Standard Name',
        TestingPost: 'Testing Post',
        Operation: 'Operation',
        remarks: 'Remarks',
        withdrawalReason: 'Reason For Withdrawal',
        PleaseSelect: 'Please Select',
        SamplingPoint: 'Sampling Point',
        productionLine: 'Production Line',
        SubcontractingOrNot: 'Subcontracting Or Not',
        Subcontractor: 'Subcontractor',
        WhetherToSignAContract: 'Whether To Sign A Contract',
        ResultJudgmentBasis: 'Result Judgment Basis',
        Fermentation: 'Fermentation Task Or Not',
        FermentationStartTime: 'Fermentation Start Time',
        FermentationEndTime: 'Fermentation End Time',
        FermentationPeriod: 'Fermentation Period',
        PlanNumber: 'Plan Number',
        PlanName: 'Plan Name',
        planDate: 'Plan Date',
        PlannedSamplingDate: 'Planned Sampling Date',
        StartSamplingDate: 'Start Sampling Date',
        ActualSamplingTime: 'Actual Sampling Time',
        SamplingPeriod: 'Sampling Period',
        StartSamplingTime: 'Start Sampling Time',
        SampleRumberingRules: 'Sample Numbering Rules',
        preservation: 'Preservation',
        speedOfProgress: 'Speed Of Progress',
        SelectDate: 'Select Date',
        ItemsSelected: 'Items Selected',
        TestAndDetectionParameters: 'Test And Detection Parameters',
        TestBasisNo: 'TestBasisNo',
        MethodCode: 'Method Code',
        MethodName: 'Method Name',
        GroupName: 'Group Name',
        Reset: 'Reset',
        ByProject: 'By Project',
        GroupBy: 'Group By',
        AddTestPlan:'Add Test Plan',
        DividePlangroups:'Divide plan groups',
        frequency:'Frequency',
        timeSlot:'Time Slot',
        DetermineFrequency:'Determine Frequency',
        NoDataTemporarily:'No Data Temporarily',
        Approver:'Approver',
        ApprovalTime:'Approval Time',
        ApprovalOpinions:'Approval Opinions',
        WithdrawalDetails:'Withdrawal Details',
        ScheduledTask:'Scheduled Task',
        TestPlanPeriod:'Test Plan Period',
        TasksTimes:'Tasks (Times)',
        DetermineThePlan: 'Determine The Plan',
        SchedulingPlan: 'Scheduling Plan',
        NewSchedule: 'New Schedule',
        download: 'Download',
        Schedule: 'Schedule',
        TaskProgress: 'Task Progress',
        DetectionProgress: 'Detection Progress',
        ReportProgress: 'Report Progress',
        PlanRemarks:'Plan Remarks',
        ActualSamplingOffsetMinutes:'Actual Sampling Offset Minutes'
    }
}
