export default {
    chinese: {
        batchEntry: '批量录入',
        sampleCode: '样品编号',
        sampleType: '样品类型',
        sampleBatchNo: '样品批号',
        itemNumber: '项目数量',
        taskNo: '任务编号',
        taskTime: '任务日期',
        operate: '操作',
        sampleName: '项目名称',
        methodNo: '方法编号',
        waitEntrySampleNumber: '待录入样品数量',
        entryUser: '录入人',
        entryTime: '录入日期',
        withdrawReason: '退回原因',
        inspectionLotId: '检验批ID',
        approvalStatus: '审批状态',
        pushSAP: '推送SAP',
        ResultEntry: '结果录入',
        ReceiveTask: '接收任务',
        ReturnTheTask: '交回任务'
    },
    english: {
        batchEntry: 'BatchEntry',
        sampleCode: 'SampleCode',
        sampleType: 'SampleType',
        sampleBatchNo: 'SampleBatchNo',
        itemNumber: 'ItemNumber',
        taskNo: 'TaskNo',
        taskTime: 'TaskTime',
        operate: 'Operate',
        sampleName: 'SampleName',
        methodNo: 'MethodNo',
        waitEntrySampleNumber: 'WaitEntrySampleNumber',
        entryUser: 'EntryUser',
        entryTime: 'EntryTime',
        withdrawReason: 'WithdrawReason',
        inspectionLotId: 'InspectionLotId',
        approvalStatus: 'ApprovalStatus',
        pushSAP: 'Push SAP',
        ResultEntry: 'Result Entry',
        ReceiveTask: 'Receive Task',
        ReturnTheTask: 'Return The Task'
    }
}
