export default {
    chinese: {
        originalRecordTitle: '录入结果',
        confirmBtn: '确定',
        cancelBtn: '取消',
        EntryOfOriginalRecords: '录入原始记录',
        taskNo: '任务编号',
        sampleBatchNo: '样品批号',
        sampleType: '样品类型',
        testItems: '检测项目',
        testInstrument: '检测仪器',
        testResult: '检测结果',
        methodNo: '方法编号',
        methodName: '方法名称',
        judgementQuota: '判定指标',
        judgementConclusion: '判定结论',
        addInstrument: '添加仪器',
        saveBtn: '保存',
        closeBtn: '取消',
        instrumentType: '仪器分类',
        instrumentNo: '仪器编号',
        instrumentName: '仪器名称',
        instrumentModel: '仪器型号',
        operate: '操作',
        selInstrumentNumber:'已选择仪器数量',
        Submit:'提交',
        PleaseEnter:'请输入',
        batchEntry: '批量录入',
    },
    english: {
        PleaseEnter:'Please Enter',
        batchEntry: 'BatchEntry',
        originalRecordTitle: 'EntryResults',
        confirmBtn: 'Confirm',
        cancelBtn: 'Cancel',
        EntryOfOriginalRecords: 'Entry Of Original Records',
        taskNo: 'TaskNo',
        sampleBatchNo: 'SampleBatchNo',
        sampleType: 'SampleType',
        testItems: 'TestItems',
        testInstrument: 'TestInstrument',
        testResult: 'TestResult',
        methodNo: 'MethodNo',
        methodName: 'MethodName',
        judgementQuota: 'JudgementQuota',
        judgementConclusion: 'JudgementConclusion',
        addInstrument: 'AddInstrument',
        saveBtn: 'Save',
        closeBtn: 'Close',
        instrumentType: 'InstrumentType',
        instrumentNo: 'InstrumentNo',
        instrumentName: 'InstrumentName',
        instrumentModel: 'InstrumentModel',
        operate: 'Operate',
        selInstrumentNumber:'Number of instruments selected',
        Submit:'Submit'
    }
}
